FROM maven:3.8.6-openjdk-18 AS build
COPY . .
RUN mvn clean packge -DskipTests

FROM  openjdk:18-jdk-slim
COPY --from=build /target/bookStore-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 1001
ENTRYPOINT [ "java","-jar","bookStore.jar" ]